import express from "express";
import path from "path";
import nodemailer from "nodemailer";
import { createServer as createViteServer } from "vite";
import dotenv from "dotenv";

// Load environment variables
dotenv.config();

async function startServer() {
  const app = express();
  const PORT = 3000;

  // Rich JSON payload capability to handle embedded/canvas-drawn base64 posters if needed
  app.use(express.json({ limit: "50mb" }));
  app.use(express.urlencoded({ limit: "50mb", extended: true }));

  // API Health check
  app.get("/api/health", (req, res) => {
    res.json({ status: "ok", service: "PowerHouse Gym Full-Stack Engine" });
  });

  // API endpoint for event registration with Gmail transmission
  app.post("/api/events/register", async (req, res) => {
    const { eventId, eventTitle, name, phone, email, googleFormUrl, googleFormSubmitted } = req.body;

    if (!name || !phone) {
      return res.status(400).json({ error: "Name and phone number are required fields." });
    }

    const recipientEmail = process.env.GYM_GMAIL || "shaikhfaizsadiq@gmail.com";
    const timestamp = new Date().toLocaleString("en-IN", { timeZone: "Asia/Kolkata" });

    // Render professional HTML notification
    const emailSubject = `🚨 NEW EVENT REGISTRATION: ${eventTitle} (Attendee: ${name})`;
    const emailHtmlBody = `
      <div style="font-family: 'Century Gothic', -apple-system, sans-serif; background-color: #0c0c0c; color: #ffffff; padding: 30px; border-radius: 16px; border: 2px solid #c9a84c; max-width: 600px; margin: auto; box-shadow: 0 10px 30px rgba(0,0,0,0.8);">
        <div style="text-align: center; border-bottom: 2px solid #c9a84c; padding-bottom: 15px; margin-bottom: 25px;">
          <h1 style="color: #c9a84c; font-size: 28px; letter-spacing: 2px; margin: 0; font-weight: bold; text-transform: uppercase;">POWER HOUSE GYM</h1>
          <p style="color: #a0a0a0; font-size: 11px; letter-spacing: 3px; font-weight: bold; margin: 5px 0 0 0;">EVENT PORTAL REGISTRATION RECORD</p>
        </div>
        
        <div style="background-color: #121212; border-left: 4px solid #c9a84c; padding: 15px 20px; border-radius: 8px; margin-bottom: 25px;">
          <h3 style="color: #c9a84c; margin-top: 0; margin-bottom: 10px; font-size: 16px; text-transform: uppercase; letter-spacing: 1px;">EVENT DETAILS</h3>
          <p style="margin: 4px 0; font-size: 14px;"><strong style="color: #c9a84c;">Event:</strong> ${eventTitle}</p>
          <p style="margin: 4px 0; font-size: 14px;"><strong style="color: #c9a84c;">Event ID:</strong> ${eventId}</p>
          <p style="margin: 4px 0; font-size: 14px;"><strong style="color: #c9a84c;">Registered On:</strong> ${timestamp}</p>
        </div>

        <div style="background-color: #121212; border-left: 4px solid #ff4a4a; padding: 15px 20px; border-radius: 8px; margin-bottom: 25px;">
          <h3 style="color: #ff4a4a; margin-top: 0; margin-bottom: 10px; font-size: 16px; text-transform: uppercase; letter-spacing: 1px;">ATTENDEE PARTICULARS</h3>
          <p style="margin: 8px 0; font-size: 14px;"><strong style="color: #c9a84c;">Full Name:</strong> ${name}</p>
          <p style="margin: 8px 0; font-size: 14px;"><strong style="color: #c9a84c;">Mobile/Phone:</strong> <a href="tel:${phone}" style="color: #ffffff; text-decoration: none; border-bottom: 1px dashed #c9a84c;">${phone}</a></p>
          <p style="margin: 8px 0; font-size: 14px;"><strong style="color: #c9a84c;">Email Identity:</strong> ${email || "Not Provided"}</p>
          ${googleFormSubmitted ? `<p style="margin: 8px 0; font-size: 14px; color: #4bf080;"><strong style="color: #4bf080;">Google Form Status:</strong> Handled in External Google Form link</p>` : ""}
        </div>

        ${googleFormUrl ? `
        <div style="text-align: center; margin-top: 20px; padding: 12px; background-color: #181818; border-radius: 8px; border: 1px dashed #555555;">
          <p style="font-size: 12px; color: #a0a0a0; margin: 0 0 8px 0;">This event is integrated with an external Google Form:</p>
          <a href="${googleFormUrl}" style="color: #c9a84c; text-decoration: none; font-size: 13px; font-weight: bold; border-bottom: 1px solid #c9a84c;" target="_blank">View Linked Google Form</a>
        </div>
        ` : ""}

        <div style="text-align: center; margin-top: 30px; border-top: 1px solid #222222; padding-top: 15px;">
          <p style="color: #666666; font-size: 10px; margin: 0;">This email is automatically generated by PowerHouse Gym & Nutrition portal.</p>
          <p style="color: #666666; font-size: 10px; margin: 3px 0 0 0;">Recipient Target: ${recipientEmail}</p>
        </div>
      </div>
    `;

    // Local audit log statement for developers and admins
    console.log(`[Event Registration Logging] Compile: ${name} registered for ${eventTitle}.`);

    let mailSentSuccessfully = false;
    let mailErrorDetails = "";

    // Check if real SMTP details are available
    const host = process.env.SMTP_HOST;
    const port = process.env.SMTP_PORT ? parseInt(process.env.SMTP_PORT) : 587;
    const user = process.env.SMTP_USER;
    const pass = process.env.SMTP_PASS;

    if (host && user && pass) {
      try {
        const transporter = nodemailer.createTransport({
          host,
          port,
          secure: port === 465, // true for port 465, false for 587
          auth: {
            user,
            pass,
          },
        });

        await transporter.sendMail({
          from: `"PowerHouse Gym Events Manager" <${user}>`,
          to: recipientEmail,
          replyTo: email || undefined,
          subject: emailSubject,
          html: emailHtmlBody,
        });

        console.log(`[SMTP Dispatch] Genuine SMTP dispatch successful to: ${recipientEmail}`);
        mailSentSuccessfully = true;
      } catch (err: any) {
        console.error("[SMTP ERROR] Failed to send email via nodemailer:", err);
        mailErrorDetails = err.message || String(err);
      }
    } else {
      console.log("[SMTP Fallback Mode] SMTP parameters are absent in .env.example/environment secrets. Successfully logged payload to administrative logs.");
    }

    res.json({
      success: true,
      smtpTriggered: host && user && pass ? true : false,
      smtpSuccess: mailSentSuccessfully,
      smtpError: mailErrorDetails,
      logRecord: {
        eventId,
        eventTitle,
        name,
        phone,
        email,
        timestamp,
      },
      message: mailSentSuccessfully 
        ? "Registration successful! Record dispatched to Gym's Gmail." 
        : (host && user && pass) 
          ? `Registration saved! However, SMTP encountered an error: ${mailErrorDetails}`
          : "Registration saved successfully! Gmail alert triggered (Running in simulator mode with detailed console logging, as SMTP coordinates are not active in environment settings)."
    });
  });

  // Vite integration middleware
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
    console.log("[Vite Middleware] Dev server active on proxy port 3000.");
  } else {
    const distPath = path.join(process.cwd(), "dist");
    app.use(express.static(distPath));
    app.get("*", (req, res) => {
      res.sendFile(path.join(distPath, "index.html"));
    });
    console.log("[Express Static] Production assets mapped from 'dist'.");
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`[Full-Stack server] Running on http://localhost:${PORT}`);
  });
}

startServer();
